baseURL = "https://hashdefine2.netlify.app/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "#Define"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

  # Author of the site, will be used in meta information
  author = "Abhishek Arya"
  # Description of the site, will be used in meta information
  description = "My notes and elucidations revolving around programming."
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  search = true
  
[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github "
identifier = "mygithub"
url = "https://github.com/abhishekarya1"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-laptop-code'></i> Blog"
identifier = "myblog"
url = "https://abhishekarya1.github.io"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 12